changelog as pre-requisite

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,9 +4,34 @@ on:
       - master
 
 jobs:
+  changelog:
+    name: Verify if CHANGELOG was updated
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+
+      - name: Get version from CHANGELOG.md
+        id: changelog_reader
+        uses: mindsers/changelog-reader-action@v2
+        with:
+          path: ./CHANGELOG.md
+
+      - name: Validate the version has not yet been used
+        env:
+          TAG: v${{ steps.changelog_reader.outputs.version }}
+        run: |
+          if git ls-remote --exit-code --tags origin "refs/tags/$TAG" >/dev/null 2>&1; then
+            echo "::error ::tag $TAG exists already"
+            exit 1
+          fi
+
   build-mac:
     name: Mac executable
     runs-on: macos-latest
+    needs: changelog
     steps:
       - uses: actions/checkout@v3
       - uses: dtolnay/rust-toolchain@stable
@@ -21,6 +46,7 @@ jobs:
   build-windows:
     name: Windows executable
     runs-on: windows-latest
+    needs: changelog
     steps:
       - uses: actions/checkout@v3
       - uses: dtolnay/rust-toolchain@stable
